[build]
  command = "npm run build:static"
  publish = "out"

[build.environment]
  NPM_FLAGS = "--legacy-peer-deps"
  SKIP_PLUGIN_INSTALL = "true"
  DISABLE_PLUGINS = "true"

[[plugins]]
  package = "" 